pipeline {
    agent any

    stages {
        stage('Pre-Test Setup') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                build 'DockerProject'
            }
        }
        stage('Post-Test') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}