pipeline {
    agent any

    stages {
        stage('Pre-Test Setup') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                build 'DockerProject'
            }
        }
        stage('Post-Test') {
            steps {
                echo 'Deploying....'
                emailext body: 'Jenkins Pipeline Build ran , please check reports', subject: 'Jenkins Pipeline Build', to: 'souviks@mindfiresolutions.com'
            }
        }
    }
}